package org.treeWare.model.core

enum class ModelElementType {
    MODEL,
    ROOT,
    ENTITY,
    PRIMITIVE_FIELD,
    ALIAS_FIELD,
    ENUMERATION_FIELD,
    ASSOCIATION_FIELD,
    COMPOSITION_FIELD,
    PRIMITIVE_LIST_FIELD,
    ALIAS_LIST_FIELD,
    ENUMERATION_LIST_FIELD,
    ASSOCIATION_LIST_FIELD,
    COMPOSITION_LIST_FIELD,
    ENTITY_KEYS
}
